import { jsPDF } from 'jspdf'
import { format } from 'date-fns'
import type { Bill } from '@/types'

const BRAND_COLOR: [number, number, number] = [79, 70, 229]

function header(doc: jsPDF, title: string) {
  doc.setFillColor(...BRAND_COLOR)
  doc.rect(0, 0, 210, 28, 'F')
  doc.setTextColor(255, 255, 255)
  doc.setFontSize(18)
  doc.setFont('helvetica', 'bold')
  doc.text('SafeWater', 14, 18)
  doc.setFontSize(11)
  doc.setFont('helvetica', 'normal')
  doc.text(title, 196, 18, { align: 'right' })
  doc.setTextColor(0, 0, 0)
}

function line(doc: jsPDF, y: number) {
  doc.setDrawColor(220, 220, 220)
  doc.line(14, y, 196, y)
}

export function generateInvoicePdf(
  bill: Bill,
  customer: { name: string; customerNumber: string; email: string },
) {
  const doc = new jsPDF()
  header(doc, 'Invoice')

  let y = 42
  doc.setFontSize(12)
  doc.setFont('helvetica', 'bold')
  doc.text(`Invoice — ${format(new Date(bill.billing_year, bill.billing_month - 1), 'MMMM yyyy')}`, 14, y)
  doc.setFont('helvetica', 'normal')
  doc.setFontSize(10)
  y += 8
  doc.text(`Billed to: ${customer.name}`, 14, y)
  y += 5
  doc.text(`Customer number: ${customer.customerNumber}`, 14, y)
  y += 5
  doc.text(`Email: ${customer.email}`, 14, y)
  y += 5
  doc.text(`Due date: ${format(new Date(bill.due_date), 'MMM d, yyyy')}`, 14, y)
  y += 5
  doc.text(`Status: ${bill.status.toUpperCase()}`, 14, y)

  y += 10
  line(doc, y)
  y += 8

  const rows: [string, string][] = [
    ['Consumption', `${bill.consumption} m³`],
    ['Amount', `$${bill.amount.toFixed(2)}`],
    ['Tax', `$${bill.tax.toFixed(2)}`],
    ['Discount', `-$${bill.discount.toFixed(2)}`],
  ]
  for (const [label, value] of rows) {
    doc.text(label, 14, y)
    doc.text(value, 196, y, { align: 'right' })
    y += 7
  }

  line(doc, y)
  y += 8
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(12)
  doc.text('Total', 14, y)
  doc.text(`$${bill.total.toFixed(2)}`, 196, y, { align: 'right' })

  doc.setFont('helvetica', 'normal')
  doc.setFontSize(8)
  doc.setTextColor(140, 140, 140)
  doc.text('This is a demo invoice generated by SafeWater. No real payment gateway is connected.', 14, 285)

  doc.save(`invoice-${bill.billing_year}-${String(bill.billing_month).padStart(2, '0')}.pdf`)
}

export interface UsageReportRow {
  date: string
  consumption: number
}

export function generateUsageReportPdf(
  customerName: string,
  meterSerial: string,
  rows: UsageReportRow[],
) {
  const doc = new jsPDF()
  header(doc, 'Usage report')

  let y = 42
  doc.setFontSize(11)
  doc.text(`Customer: ${customerName}`, 14, y)
  y += 6
  doc.text(`Meter: ${meterSerial}`, 14, y)
  y += 6
  doc.text(`Generated: ${format(new Date(), 'MMM d, yyyy')}`, 14, y)
  y += 6
  const total = rows.reduce((sum, r) => sum + r.consumption, 0)
  doc.text(`Total consumption: ${total.toFixed(1)} m³ over ${rows.length} days`, 14, y)

  y += 10
  line(doc, y)
  y += 8

  doc.setFont('helvetica', 'bold')
  doc.text('Date', 14, y)
  doc.text('Consumption (m³)', 196, y, { align: 'right' })
  doc.setFont('helvetica', 'normal')
  y += 6
  line(doc, y - 3)

  for (const row of rows) {
    if (y > 280) {
      doc.addPage()
      y = 20
    }
    doc.text(format(new Date(row.date), 'MMM d, yyyy'), 14, y)
    doc.text(row.consumption.toFixed(1), 196, y, { align: 'right' })
    y += 6
  }

  doc.save('usage-report.pdf')
}
